### PR TITLE
Update location on drop(trash)

### PR DESCRIPTION
**Pull request by catch222**
Seems impossible to get the updated fen string on trash/drop without
this. (I'm printing the fen string out on any user activity).

### CODE REVIEW

**Comment by oakmac** [comment]
I'm not sure about this.

Can you provide an example where the [onChange](http://chessboardjs.com/docs#config:onChange) event does **not** fire when the position changes?

**Comment by catch222** [comment]
On the onChange event I've tried outputting <a href="http://chessboardjs.com/docs#position_object">ChessBoard.objToFen(newPos)</a> and <a href="http://chessboardjs.com/docs#methods:fen">Chessboard.fen()</a> and calls to other functions. It definitely fires. It just appears that Chessboard.fen()/ChessBoard.objToFen(newPos) get the previous value. Forcing me to update it on the next event, which is a pain if you want to output a current FEN string when a piece is trashed. 
It may be a specific issue with my application, but this seemed to be the only solution I could come up with.
Here's an example:
<a href="https://github.com/catch222/ChessboardJSTest/blob/master/test.html">test.html</a>

**Comment by oakmac** [comment]
The `onChange` method receives two arguments: the old position and the new position.

I think this is what you're looking for.

**Comment by catch222** [comment]
Ah I see, when I tried <code>ChessBoard.objToFen(newPos)</code> on the <code>onChange</code> event, I was also running <code>board.fen()</code> from another function, which was overriding it.

I'm guessing the return value from calling <code>board.fen()</code> would be up to date after the <code>onChange</code> event? It appears to work with the <code>onMoveEnd</code> event, but that doesn't fire when a piece is trashed.

**Comment by oakmac** [comment]
Correct. The `onChange` event is passed the old FEN and the new FEN. In your case, I would suggest using the new FEN that is passed into the `onChange` function to update the DOM.

**Pull request closed without merging**
