### PR TITLE
add common js compatible export

### PR DESCRIPTION
**Pull request by ofraski**
The build failed the standard JS linting but introduced more changes than I thought you'd like

### CODE REVIEW

**Comment by vesper8** [comment]
will this PR allow us to do something like 

```
import ChessBoard from '@chrisoakman/chessboardjs';
```

or

```
import '@chrisoakman/chessboardjs';
```

In a Vue/React project? If so... please can you merge it @oakmac ! : )

**Comment by ofraski** [comment]
Sorry, needs revision! :/

**Comment by ofraski** [comment]
@vesper8 newer PR actually has a chance.

The following worked

`import { Chessboard } from './chessboard-1.0.0.js'`

**Comment by honkskillet** [comment]
@ofraski that doesn't seem to work for me

**Pull request closed without merging**
